# Topic 7. Unsupervised learning: PCA and clustering

In [1]:
import numpy as np

In [3]:
s = np.array([[3, 5, 6, 7], [8, 1, 9, 4], [5, 7, 3, 0]])

In [4]:
s

array([[3, 5, 6, 7],
       [8, 1, 9, 4],
       [5, 7, 3, 0]])

In [5]:
np.ravel(s)

array([3, 5, 6, 7, 8, 1, 9, 4, 5, 7, 3, 0])

In [7]:
s.reshape(1, -1)

array([[3, 5, 6, 7, 8, 1, 9, 4, 5, 7, 3, 0]])